drop table unit_test_table if exists;
create table unit_test_table
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 98) PRIMARY KEY NOT NULL,
    username         varchar(10)                                                         null,
    deleted          boolean                                                             null,
    account_type     int                                                                 null,
    create_date_time timestamp                                                           null
);

insert into unit_test_table
values (1, '里面', 0, 201, '2019-09-04 15:01:23');
insert into unit_test_table
values (2, '即可', 0, 101, '2018-11-04 21:11:13');
insert into unit_test_table
values (3, '王五', 0, 12, '2019-08-15 20:23:44');
insert into unit_test_table
values (4, '马玉', 0, 12, '2019-09-04 20:01:22');
insert into unit_test_table
values (5, '测试', 0, 12, '2019-09-04 20:01:45');